name: Release
on: { push: { branches: [ main ], tags: [ 'v*' ] } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
            distribution: temurin
            java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup android keystore
        run: |
          base64 -d <<<'${{ secrets.ANDROID_SIGNING_KEY_STORE }}' > android.jks
          echo "ANDROID_KEYSTORE_PATH=$GITHUB_WORKSPACE/android.jks" >> $GITHUB_ENV
          # Once the path is set, we need to be able to load it
          echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_KEY_NAME=Github CI" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_KEY_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Update version code
        run: |
          ./gradlew increaseVersionCode

          git config user.email "ci-update-version-code[bot]@users.noreply.github.com"
          git config user.name "ci-update-version-code[bot]"

          git add version.properties
          git commit -m 'Increase version code'

          git push origin ${{ github.ref }}
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Update version.properties for release
        run: |
          sed -i 's/VERSION_NAME=.*/VERSION_NAME='${GITHUB_REF##*/}'/g' version.properties
          sed -i 's/VERSION_CODE=.*/VERSION_CODE=1/g' version.properties
        if: "startsWith(github.ref, 'refs/tags/')"


      - name: Build apk
        run: |
          ./gradlew assembleRelease

      - name: Build aab
        run: |
          ./gradlew bundleRelease

      - name: Publish beta release
        run: |
          ./gradlew publishReleaseBundle --track 'internal' --release-name '${{ github.sha }}'
        env:
          ANDROID_PUBLISHER_CREDENTIALS: '${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}'
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Publish named release
        run: |
          ./gradlew publishReleaseBundle --track 'production' --release-name "${GITHUB_REF##*/}"
        env:
          ANDROID_PUBLISHER_CREDENTIALS: '${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}'
        if: "startsWith(github.ref, 'refs/tags/')"
